### ISSUE TITLE
uhhh... wont run i guess?

### ISSUE THREAD

**Issue by j3rr7** [JakeMakesStuff/DCustomRPC#16]
```
Traceback (most recent call last):
  File "dcustomrpc.pyw", line 2, in <module>
    import pypresence
  File "C:\Users\adgry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pypresence\__init__.py", line 7, in <module>
    from .client import Client
  File "C:\Users\adgry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pypresence\client.py", line 8, in <module>
    from .utils import *
  File "C:\Users\adgry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pypresence\utils.py", line 20
    create_task = asyncio.async

```
![capture](https://user-images.githubusercontent.com/29926331/42277350-44108faa-7fc1-11e8-9c67-b593b7b09f12.PNG)

what and how to fix this issue ?

**Comment by JakeMakesStuff** [comment]
@j3rr7 I am aware of this issue. PyPresence has been patched to fix this and the owner will upload to Pip when "when im home on the 8th". I can suggest running `py -m pip install -e git+https://github.com/qwertyquerty/pypresence#egg=pypresence` for the meantime with Git for Windows installed.

**Comment by j3rr7** [comment]
thanks
